import { test, expect } from '@playwright/test';

test.use({
  permissions: ['geolocation'],
  geolocation: { latitude: 41.73698, longitude: -111.83384 },
});

test('test', async ({ page, context }) => {
  test.setTimeout(90000); 
  page.setDefaultTimeout(90000);
  page.setDefaultNavigationTimeout(60000);
  await context.grantPermissions(['geolocation'], { origin: 'http://localhost:8000' });
  await page.goto('http://localhost:8000/#/');
  await page.getByRole('link', { name: 'Sign up here!' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('Test');
  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('Test');
  await page.getByRole('textbox', { name: 'Username *' }).click();
  await page.getByRole('textbox', { name: 'Username *' }).fill('Test01');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('Test@example.com');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('Test!!');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByText('add_circleCreate GigPost a').click();
  await page.getByRole('textbox', { name: 'Item' }).click();
  await page.getByRole('textbox', { name: 'Item' }).fill('Test');
  await page.getByRole('textbox', { name: 'Street Address' }).first().click();
  await page.getByRole('textbox', { name: 'Street Address' }).first().fill('1550 N Main St');
  await page.getByRole('textbox', { name: 'City' }).first().click();
  await page.getByRole('textbox', { name: 'City' }).first().fill('Logan');
  await page.getByRole('textbox', { name: 'State' }).first().click();
  await page.getByRole('textbox', { name: 'State' }).first().fill('UT');
  await page.getByRole('textbox', { name: 'Zip Code' }).first().click();
  await page.getByRole('textbox', { name: 'Zip Code' }).first().fill('84341');
  await page.getByRole('checkbox', { name: 'Same as pickup address' }).check();
  await page.getByRole('spinbutton', { name: 'Budget ($)' }).click();
  await page.getByRole('spinbutton', { name: 'Budget ($)' }).fill('10');
  await page.getByRole('button', { name: 'Create Gig', exact: true }).click();
  await page.waitForLoadState('load');
  await page.waitForLoadState('domcontentloaded');
  await page.waitForLoadState('networkidle');
  await page.waitForSelector('iframe[title*="PayPal"]', { timeout: 10000 });
  const paypalFrame = page.locator('iframe[title*="PayPal"]').first().contentFrame();
  const [popup] = await Promise.all([
    page.waitForEvent('popup'), // The action that triggers the popup
    paypalFrame.getByRole('link', { name: 'PayPal', exact: true }).click()
  ]);
  await popup.waitForLoadState('load');
  await popup.waitForLoadState('domcontentloaded');
  await popup.waitForLoadState('networkidle');
  await popup.getByRole('textbox', { name: 'Email or mobile number' }).fill('Dater@personal.example.com');
  await popup.getByRole('button', { name: 'Next' }).click();
  await popup.waitForLoadState('load');
  await popup.waitForLoadState('domcontentloaded');
  await popup.getByRole('button', { name: 'Try another way' }).click();
  await popup.getByRole('button', { name: 'Use password instead' }).click();
  await popup.getByRole('textbox', { name: 'Password' }).fill('I-Am-A-Dater');
  await popup.getByRole('button', { name: 'Log In' }).click();
  await popup.getByRole('button', { name: 'Pay $' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'logout Logout' }).click();
  await page.getByRole('link', { name: 'Sign up here!' }).click();
  await page.getByRole('radio', { name: 'Cupid' }).check();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('cupid');
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('man');
  await page.getByRole('textbox', { name: 'Username *' }).fill('cupid');
  await page.getByRole('textbox', { name: 'Email is required Email *' }).fill('cupid@cupid.com');
  await page.getByRole('textbox', { name: 'Password *' }).fill('password');
  await page.getByRole('textbox', { name: 'PayPal email is required for' }).fill('Cupid@personal.example.com');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.waitForLoadState('load');
  await page.waitForLoadState('domcontentloaded');
  await page.getByRole('button', { name: 'Claim' }).click();
  await page.waitForLoadState('load');
  await page.waitForLoadState('domcontentloaded');
  await page.waitForResponse(
    resp => resp.url().includes('/api/gig/'),
    { timeout: 30000 }
  );
  await page.getByText('searchActive Gigs', { exact: true }).click();
  await page.waitForLoadState('load');
  await page.waitForLoadState('domcontentloaded');
  await page.getByRole('button', { name: 'Complete', exact: true }).click();
  await page.waitForLoadState('load');
  await page.waitForLoadState('domcontentloaded');
  await page.getByText('assignment_turned_inCompleted').click();
  await page.waitForLoadState('load');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.getByRole('heading', { name: 'Completed Gigs' })).toBeVisible();
  await expect(page.locator('div').filter({ hasText: 'Dater: Test TestItems' }).nth(2)).toBeVisible();
  await expect(page.getByRole('main')).toContainText('Dater: Test Test');
  await expect(page.getByRole('main')).toContainText('Items requested: Test');
  await expect(page.getByRole('main')).toContainText('Budget: $10.00');
  await expect(page.getByRole('main')).toContainText('Pickup Location: 1550 N Main St, Logan, UT, 84341');
  await expect(page.getByRole('button', { name: 'Rate Dater' })).toBeVisible();
  await page.getByRole('button', { name: 'Rate Dater' }).click();
  await expect(page.getByText('RateSendCancel')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Rate' })).toBeVisible();
  await expect(page.getByLabel('')).toBeVisible();
  await expect(page.locator('.row')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Send' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
  await page.getByLabel('').click();
  await page.getByLabel('').fill('Good');
  await page.locator('path').nth(3).click();
  await page.getByRole('button', { name: 'Send' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'logout Logout' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('Test@example.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test!!');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'feedback Feedback' }).click();
  await page.waitForLoadState('load');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('div').filter({ hasText: /^Feedback$/ })).toBeVisible();
  await expect(page.getByText('/5 HeartsGood')).toBeVisible();
  await expect(page.locator('.hearts-row')).toBeVisible();
  await expect(page.getByRole('main')).toContainText('4/5 Hearts');
  await expect(page.getByRole('main').getByRole('paragraph')).toContainText('Good');
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'work Gigs' }).click();
  await page.getByRole('button', { name: 'Rate Cupid' }).click();
  await page.getByLabel('').click();
  await page.getByLabel('').fill('Bad');
  await page.locator('path').first().click();
  await page.getByRole('button', { name: 'Send' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'logout Logout' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('Teest@example.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Teest!!');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'feedback Feedback' }).click();
  await expect(page.getByText('/5 HeartsBad')).toBeVisible();
  await expect(page.locator('.hearts-row')).toBeVisible();
  await expect(page.getByRole('main')).toContainText('1/5 Hearts');
  await expect(page.getByRole('main').getByRole('paragraph')).toContainText('Bad');
});