# Generated by Django 5.0.2 on 2025-10-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dater_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='dropoff_location',
            field=models.TextField(null=True),
        ),
    ]
