# Generated by Django 5.0.2 on 2025-11-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_quest_dropoff_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email for receiving payments', max_length=254, null=True),
        ),
    ]
