# Generated by Django 5.0.2 on 2025-11-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='payment_id',
            field=models.CharField(blank=True, help_text='PayPal payment/order ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='payout_id',
            field=models.CharField(blank=True, help_text='PayPal payout batch ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
