# Generated by Django 5.0.2 on 2025-11-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gig_payment_id_gig_payout_id_gig_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupid',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email for receiving payments', max_length=254, null=True),
        ),
    ]
