# Generated by Django 5.0.2 on 2025-11-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cupid_paypal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupid',
            name='paypal_email',
            field=models.EmailField(help_text='PayPal email for receiving payments', max_length=254, null=True),
        ),
    ]
