# Generated by Django 5.0.2 on 2025-11-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cupid_paypal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paypal_email',
        ),
    ]
