# Generated by Django 5.0.2 on 2025-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='date_time_of_drop',
            field=models.DateTimeField(null=True),
        ),
    ]
