# Generated by Django 5.0.2 on 2025-11-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gig_date_time_of_drop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupid',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='location',
        ),
    ]
