# Generated by Django 5.0.2 on 2025-11-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_cupid_location_remove_dater_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dater',
            name='dating_strengths',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='dating_weaknesses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='nerd_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='past',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dater',
            name='relationship_goals',
            field=models.TextField(blank=True, default=''),
        ),
    ]
