# Generated by Django 5.0.2 on 2025-11-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_dater_dating_strengths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='user',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='PaymentCard',
        ),
    ]
