# Generated by Django 5.0.2 on 2025-11-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_paymentcard_user_delete_bankaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dater',
            name='dating_strengths',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='dating_weaknesses',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='nerd_type',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='past',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='relationship_goals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
